# Generated by Django 4.1.2 on 2023-02-09 17:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="individual_create",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AngelListLink", models.URLField(verbose_name="Angellist link")),
                ("CrunchbaseLink", models.URLField(verbose_name="Crunchbase link")),
                ("LinkedInLink", models.URLField(verbose_name="Linkedin link")),
                ("Company", models.CharField(max_length=100, verbose_name="Company")),
                (
                    "Position",
                    models.CharField(max_length=100, verbose_name="Company position"),
                ),
                ("Email", models.EmailField(max_length=254)),
                (
                    "PrimaryNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Primary phone number"
                    ),
                ),
                (
                    "SecondaryNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Secondary phone number",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="residentialAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(max_length=50, verbose_name="Address line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Address line 2"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="State/Province"
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.individual_create",
                    ),
                ),
            ],
        ),
    ]
