# Generated by Django 4.1.2 on 2023-02-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="individual_create",
            new_name="individual_model",
        ),
    ]
