# Generated by Django 4.1.2 on 2023-03-09 16:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dateInvested',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 9))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='portfolio.company'),
        ),
        migrations.AlterField(
            model_name='pastexperience',
            name='end_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('VENTURE_CAPITAL', 'Venture Capital'), ('PRIVATE_EQUITY_FIRM', 'Private Equity Firm'), ('ACCELERATOR', 'Accelerator'), ('INVESTMENT_PARTNER', 'Investment Partner'), ('CORPORATE_VENTURE_CAPITAL', 'Corporate Venture Capital'), ('MICRO_VC', 'Micro VC'), ('ANGEL_GROUP', 'Angel Group'), ('INCUBATOR', 'Incubator'), ('INVESTMENT_BANK', 'Investment Bank'), ('FAMILY_INVESTMENT_OFFICE', 'Family Investment Office'), ('VENTURE_DEBT', 'Venture Debt'), ('CO_WORKING_SPACE', 'Co-Working Space'), ('FUND_OF_FUNDS', 'Fund Of Funds'), ('HEDGE_FUND', 'Hedge Fund'), ('GOVERNMENT_OFFICE', 'Government Office'), ('UNIVERSITY_PROGRAM', 'University Program'), ('ENTREPRENEURSHIP_PROGRAM', 'Entrepreneurship Program'), ('SECONDARY_PURCHASER', 'Secondary Purchaser'), ('STARTUP_COMPETITION', 'Startup Competition'), ('SYNDICATE', 'Syndicate'), ('PENSION_FUNDS', ' Pension Funds')], default='VC', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='portfolio.company')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='portfolio.individual')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.investment')),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='portfolio.investor'),
        ),
    ]
