# Generated by Django 4.1.2 on 2023-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastexperience",
            name="end_year",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
