# Generated by Django 4.1.2 on 2023-03-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="content_type",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
