# Generated by Django 4.1.2 on 2023-02-20 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_registration_number',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Company Registration Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=50, verbose_name='Jurisdiction'),
        ),
        migrations.AddField(
            model_name='company',
            name='previous_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registered Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
        migrations.AddField(
            model_name='individual',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cohort', models.PositiveIntegerField()),
                ('coaches_mentors', models.ManyToManyField(to='portfolio.individual')),
                ('participants', models.ManyToManyField(related_name='participants', to='portfolio.portfolio_company')),
                ('partners', models.ManyToManyField(related_name='partners', to='portfolio.company')),
            ],
        ),
    ]
