# Generated by Django 4.1.2 on 2023-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="founder",
            name="company",
        ),
        migrations.AddField(
            model_name="founder",
            name="company",
            field=models.CharField(default="USA", max_length=100),
        ),
    ]
