# Generated by Django 4.1.2 on 2023-02-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individual",
            name="is_archived",
        ),
    ]
