# Generated by Django 4.1.2 on 2023-02-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cohort', models.PositiveIntegerField()),
                ('coaches_mentors', models.ManyToManyField(to='portfolio.individual')),
                ('participants', models.ManyToManyField(related_name='participants', to='portfolio.portfolio_company')),
                ('partners', models.ManyToManyField(related_name='partners', to='portfolio.company')),
            ],
        ),
    ]
