# Generated by Django 4.1.2 on 2023-03-10 17:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models.document_model


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorIndividual',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.individual')),
                ('NumberOfPortfolioCompanies', models.PositiveIntegerField()),
                ('NumberOfPersonalInvestments', models.PositiveIntegerField()),
                ('NumberOfPartnerInvestments', models.PositiveIntegerField()),
                ('PartOfIncubator', models.BooleanField()),
                ('NumberOfExits', models.PositiveIntegerField()),
            ],
            bases=('portfolio.individual',),
        ),
        migrations.AddField(
            model_name='programme',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dateInvested',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 10))]),
        ),
        migrations.AlterField(
            model_name='investment',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to='portfolio.company'),
        ),
        migrations.AlterField(
            model_name='pastexperience',
            name='end_year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('VENTURE_CAPITAL', 'Venture Capital'), ('PRIVATE_EQUITY_FIRM', 'Private Equity Firm'), ('ACCELERATOR', 'Accelerator'), ('INVESTMENT_PARTNER', 'Investment Partner'), ('CORPORATE_VENTURE_CAPITAL', 'Corporate Venture Capital'), ('MICRO_VC', 'Micro VC'), ('ANGEL_GROUP', 'Angel Group'), ('INCUBATOR', 'Incubator'), ('INVESTMENT_BANK', 'Investment Bank'), ('FAMILY_INVESTMENT_OFFICE', 'Family Investment Office'), ('VENTURE_DEBT', 'Venture Debt'), ('CO_WORKING_SPACE', 'Co-Working Space'), ('FUND_OF_FUNDS', 'Fund Of Funds'), ('HEDGE_FUND', 'Hedge Fund'), ('GOVERNMENT_OFFICE', 'Government Office'), ('UNIVERSITY_PROGRAM', 'University Program'), ('ENTREPRENEURSHIP_PROGRAM', 'Entrepreneurship Program'), ('SECONDARY_PURCHASER', 'Secondary Purchaser'), ('STARTUP_COMPETITION', 'Startup Competition'), ('SYNDICATE', 'Syndicate'), ('PENSION_FUNDS', ' Pension Funds')], default='VC', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='portfolio.company')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='portfolio.individual')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Document name must consist of up to 254 valid characters: 0-9 a-z A-Z _ \\ - . and spaces', regex='^[0-9a-zA-Z_\\-. ]+$')])),
                ('file_type', models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='Document type must consist of up to 254 valid characters: 0-9 a-z A-Z _ \\ - . and spaces', regex='^[0-9a-zA-Z_\\-. ]+$')])),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=portfolio.models.document_model.get_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.company')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.investment')),
            ],
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='portfolio.investor'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file__gt', ''), ('url__isnull', True)), models.Q(('file__exact', ''), ('url__isnull', False)), _connector='OR'), name='portfolio_document_url_or_file'),
        ),
    ]
