# Generated by Django 4.1.2 on 2023-03-06 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models.document_model


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Document name must consist of up to 254 valid characters: 0-9 a-z A-Z _ \\ - . and spaces', regex='^[0-9a-zA-Z_\\-. ]+$')])),
                ('file_type', models.CharField(max_length=254, validators=[django.core.validators.RegexValidator(message='Document type must consist of up to 254 valid characters: 0-9 a-z A-Z _ \\ - . and spaces', regex='^[0-9a-zA-Z_\\-. ]+$')])),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=portfolio.models.document_model.get_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file__gt', ''), ('url__isnull', True)), models.Q(('file__exact', ''), ('url__isnull', False)), _connector='OR'), name='portfolio_document_url_or_file'),
        ),
    ]
