# Generated by Django 4.1.2 on 2023-02-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pastexperience",
            old_name="ndividual",
            new_name="individual",
        ),
    ]
