# Generated by Django 4.1.2 on 2023-03-04 00:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investment_contractright_programme_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorIndividual',
            fields=[
                ('individual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.individual')),
                ('NumberOfPortfolioCompanies', models.PositiveIntegerField()),
                ('NumberOfPersonalInvestments', models.PositiveIntegerField()),
                ('NumberOfPartnerInvestments', models.PositiveIntegerField()),
                ('PartOfIncubator', models.BooleanField()),
                ('NumberOfExits', models.PositiveIntegerField()),
            ],
            bases=('portfolio.individual',),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dateInvested',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 4))]),
        ),
    ]
