# Generated by Django 4.1.2 on 2023-02-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='Name',
            field=models.CharField(default='Test-name', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
