# Generated by Django 4.1.2 on 2023-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
    ]
