# Generated by Django 4.1.2 on 2023-02-20 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_company_company_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='programme',
            name='cohort',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='cohort has to be at least 1')]),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('name', 'cohort')},
        ),
    ]
