# Generated by Django 4.1.2 on 2023-02-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_founder_company_founder_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="founder",
            old_name="company",
            new_name="companyFounded",
        ),
    ]
