# Generated by Django 4.1.2 on 2023-03-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_investment_dateinvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='contractRight',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
