# Generated by Django 4.1.3 on 2023-03-13 01:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_individual_profile_pic_alter_investment_dateinvested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.ImageField(blank=True, default='currentuser.jpg', upload_to='individuals/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='dateInvested',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 13))]),
        ),
    ]
