# Generated by Django 4.1.2 on 2023-02-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_individual_create_individual_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='individual_model',
            new_name='Individual',
        ),
    ]
