# Generated by Django 4.1.2 on 2023-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_individual_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
