# Generated by Django 4.1.2 on 2023-02-21 22:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_investorindividual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="dateInvested",
            field=models.DateTimeField(
                auto_now=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=django.utils.timezone.now
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="startup",
            field=models.ManyToManyField(
                related_name="startup", to="portfolio.portfoliocompany"
            ),
        ),
    ]
