# Generated by Django 4.1.2 on 2023-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_company_company_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='cover',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
