# Generated by Django 4.1.2 on 2023-03-21 20:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_document_individual_document_programme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='dateInvested',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 21))]),
        ),
        migrations.DeleteModel(
            name='InvestorIndividual',
        ),
    ]
