# Generated by Django 4.1.2 on 2023-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_investorindividual_programme_cover_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='investor',
            constraint=models.CheckConstraint(check=models.Q(('company__isnull', True), ('individual__isnull', True), _connector='OR'), name='only_one_field_set'),
        ),
    ]
