# Generated by Django 4.1.2 on 2023-03-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_programme_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
