# Generated by Django 4.1.2 on 2023-02-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_investment_dateinvested_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individual",
            name="isFounder",
        ),
        migrations.AlterField(
            model_name="founder",
            name="companyFounded",
            field=models.CharField(default="startup", max_length=100),
        ),
    ]
