# Generated by Django 4.1.2 on 2023-02-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_individual_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='Name',
            new_name='name',
        ),
    ]
