# Generated by Django 4.1.2 on 2023-02-15 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_individual_model_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
    ]
