# Generated by Django 4.1.2 on 2023-02-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_company_name_alter_company_previous_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
