# Generated by Django 4.1.2 on 2023-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_company_founder_companyfounded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="isFounder",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
