# Generated by Django 4.1.3 on 2023-03-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_individual_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultuser.jpg', upload_to='individuals/', verbose_name='Profile picture'),
        ),
    ]
