# Generated by Django 4.1.2 on 2023-03-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_document_document_portfolio_document_url_or_file'),
        ('portfolio', '0003_investorindividual_alter_investment_dateinvested'),
    ]

    operations = [
    ]
