# Generated by Django 4.1.2 on 2023-03-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_company_parent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_company',
            name='parent_company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_company', to='portfolio.company'),
        ),
    ]
