# Generated by Django 4.1.2 on 2023-03-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_document_individual_document_programme_and_more'),
        ('portfolio', '0004_alter_investment_dateinvested_and_more'),
    ]

    operations = [
    ]
