# Generated by Django 4.1.2 on 2023-02-15 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_registration_number',
            field=models.CharField(default='00000000', max_length=8, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Company Registration Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=50, verbose_name='Jurisdiction'),
        ),
        migrations.AddField(
            model_name='company',
            name='previous_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
