# Generated by Django 4.1.2 on 2023-02-24 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_programme_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='cover',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
