# Generated by Django 4.1.2 on 2023-02-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_founder_companyfounded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="companyFounded",
            field=models.CharField(default="startup", max_length=100),
        ),
    ]
