# Generated by Django 4.1.2 on 2023-03-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_investment_dateinvested_and_more'),
        ('portfolio', '0005_merge_20230321_2143'),
    ]

    operations = [
    ]
