# Generated by Django 4.1.2 on 2023-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_company_incorporation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registered Address'),
        ),
    ]
