# Generated by Django 4.1.3 on 2023-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_individual_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profilepics', verbose_name='Profile picture'),
        ),
    ]
