# Generated by Django 4.1.2 on 2023-03-09 17:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_investment_dateinvested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="dateInvested",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 3, 9)
                    )
                ]
            ),
        ),
    ]
