# Generated by Django 4.1.2 on 2023-02-19 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_company_registered_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='previous_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='trading_names',
            field=models.CharField(blank=True, max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Company name must consist of three to sixty characters', regex='^[a-zA-Z0-9 ,]{3,}$')]),
        ),
    ]
