# Generated by Django 4.1.2 on 2023-03-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_investment_contractright_and_more'),
        ('portfolio', '0007_alter_individual_profile_pic'),
    ]

    operations = [
    ]
